version: '3'
services:
  postgres:
    image: "postgres:${POSTGRES_VERSION:-latest}"
    command: ["-d", "postgres"]
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=password
    restart: unless-stopped
  mysql:
    image: "mysql:${MYSQL_VERSION:-latest}"
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=password
    restart: unless-stopped
  redis:
    image: "redis:${REDIS_VERSION:-latest}"
    ports:
      - "6379:6379"
    restart: unless-stopped
  memcached:
    image: "memcached:${MEMCACHED_VERSION:-latest}"
    expose:
      - "11211"
    ports:
      - "11211:11211"
    command: memcached -p 11211 -m 64
    restart: unless-stopped
  s3mock:
    image: "rasodu/s3mock:0.2.1"
    command: -r /fakes3_root -p 4569
    ports:
      - "4569:4569"
    restart: unless-stopped
  beanstalkd:
    image: "rasodu/beanstalkd:v1.10.1"
    expose:
      - "11300"
    ports:
      - "11300:11300"
    restart: unless-stopped
  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
      - "1025:25"
    restart: unless-stopped
